services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    working_dir: /app/apps
    command: python app.py
    restart: unless-stopped

  # web_fastapi:
  #   build: .
  #   ports:
  #     - "5001:5000"
  #   volumes:
  #     - .:/app
  #   working_dir: /app/apps
  #   command: uvicorn app_fastapi:app --host 0.0.0.0 --port 5000 --reload
  #   restart: unless-stopped

  test_api:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    working_dir: /app/apps
    command: python test_server.py
    restart: unless-stopped
